### ISSUE TITLE
Use narrower types for small BCD

### ISSUE THREAD

**Issue by rmja** [rlkandela/bcd-numbers#3]
It would be really useful if `BCD::new()` and `get_number()` did not always use `u256`.
For example `BCD::<4>::new(...)` should only take `u32` as its value can never exceed the range of that value. Relying on `u256` is limiting for embedded use that does not natively support the type.

**Comment by rlkandela** [comment]
There is `BCD::<4>::try_from(5u32)` but I will try to make it more usable. At this time its a bit akward to create a `BCD::<3>` from a valid `u32`.
